### ISSUE TITLE
a bug with batteries

### ISSUE THREAD

**Issue by Zscreeper** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1437]
https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/assets/130389090/a345bf53-8d8a-4325-9eb3-13b492c709a2

after updating the mod, this happened

**Comment by HbmMods** [comment]
The priority breaking should have been fixed with X4936, the version that came out today. The power oscillating in large clusters of energy storage blocks is normal and usually not an issue.

**Comment by Zscreeper** [comment]
previously, before the 4935 update, the fluctuations were scanty, but now they have become very strong and 12 of my batteries were broken, I tried to break them and install them, but the bug remained most likely due to the preservation of nbt data, I do not know for sure if nbt data was in 1.7.10 minecraft

**Comment by HbmMods** [comment]
Power oscillating between buffers seems to be fixed in X4942.
