### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by re7gog** [HbmMods/Hbm-s-Nuclear-Tech-GIT#1551]
Tried to enable PRISM on Crucible with graalvm 21, got this funny error, I think it's Crucible problem (Yes my setup is bug creator)
[prism-err.txt](https://github.com/user-attachments/files/15914011/prism-err.txt)
(On client with graalvm 17 ee works good)

**Comment by HbmMods** [comment]
What version are you running? That issue should have been resolved with X4998.

**Comment by re7gog** [comment]
Upgraded to X5000, issue still here
I think it's same issue again(with world dimensions paths), will try to fix by myself first

**Comment by HbmMods** [comment]
There's a confirmed crash in X5000 regarding dimensions, but it's a different problem from the previous one. It should be fixed in the development versions, the fix will be out probably on sunday.

**Comment by re7gog** [comment]
Bruh, after compiling from git throws another error about no set background image method in tabs
Please add check for world dirs like I did in [cb0eb42](https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT/commit/cb0eb4271b39b20d86839c20024436561a757e0d), I almost sure it's the problem

**Comment by re7gog** [comment]
They did this shit for compatibilty with bukkit plugins

**Comment by HbmMods** [comment]
I'm not sure what the world dir check has to do with the radiation system, unlike the pollution system the radiation system is based on chunks and therefore uses the Forge provided events for loading and saving, there's no file operators involved at all. In fact there's not a whole lot I can do with the exact error message.
