### ISSUE TITLE
So, about Desh (Problems and Design Questions)

### ISSUE THREAD

**Issue by GregoriusT** [HbmMods/Hbm-s-Nuclear-Tech-GIT#316]
### Describe the bug

I have noticed quite a few things about Desh, which still hold true for the Version you just Released an hour or two ago:

1. Desh Tools may use OreDict for the Ingots in the Recipe now, but they dont use "stickWood" for the Handle of the Recipe.

2. Desh Tool Crafting Recipes seem identical to what I remember the Galacticraft Recipe to be. Maybe turning the Recipes upside down could help avoiding Recipe conflicts? I know Forestry does it for its Bronze Tools.

3. Desh Tools seem to have Infinite Durability (May be intended considering their insane Recipe, not like Durability matters at THAT stage in the Game).

4. "Size 15 Solid Fuel Fuselage" Does not use OreDict for "ingotDesh".

5. Wouldn't Galacticraft make it super easy to bypass all the Progression about Desh when going to Mars?

6. Why is your Desh colored Red even though Galacticrafts original Desh is Black? (apart from Red being obviously better looking and fitting the "Worker's Alloy" Theme)

7. The Chemistry Template Texture for Desh Production (and all others) kindof looks like the Woodman Face from Mega Man II to me. >:]

8. Also damnit, your Default Crane Controls overlapped with my Arrow Keys for Movement, so I thought your Desh Tools have some sort of -100% Speed Effect. XD

### Please solve this equation to x

x²+3x-19=√(9x²)+6

Everybody asks to solve for X, but I ask Y to solve?

I already "solved" that one last time (and I toootally did not cheat using Wolfram Alpha), maybe get a new equation?

**Comment by divine-ray** [comment]
i forgot when bob fixed this, but 5. has been fixed some time ago by removing the ore dictionary or desh or removing it

EDIT: sorry my bad relied myself on unofficial informations

**Comment by HbmMods** [comment]
1. Many recipes still don't use ore dict when they absolutely should, I'm always fixing a few of them here and there but there's still a ton left.
2. Originally ore dict for tool and armor recipes was omitted for this very reason, much to the dismay of a lot of people. I ended up adding ore dict recipes since all packs that ran NTM already had NoMoreRecipeConflicts in it, so that issue largely took care of itself. In case that still poses a problem, I'll have to get creative.
3. Desh tools do indeed have infinite durability, but they are comparatively slow (to, say, advanced alloy which is a lot cheaper as well) and only have a harvest level of iron, making desh picks into fallback tools at best.
4. Same issue as 1
5. That is a commonly enjoyed feature, although we did conclude that having a planet full of that stuff is rather overpowered. Not too long ago I've had the idea to change NTM's desh's ore dict into something else (maybe "DeshAlloy"?) and adding a chemplant recipe converting martian desh, oil and mercury into desh alloy. The recipe would still be considerably cheaper than the original way, but balanced around the initial investment of getting to mars in the first place. I kinda forgot about that idea not long after GT started considering NTM's clusterfuck composition of desh as the "canon" alloy.
6. Originally desh wasn't intended to be ore dicted, nor compatible with GC. The idea for the red metal ingot came from the Doctor Who episode "42" which takes place on a rather industrial-looking space station that features mostly red metal walls. The name was chosen because at the time I vaguely remembered something along those lines already being part of a space mod (GC, as it turns out!) and that the name originates from Star Wars, somehow.
7. I don't think that's an issue, just grab the Metal Blade beforehand and you should be fine.
8. I neither understand why keybinds lock up just because they're assigned twice (my keybind handler certainly doesn't look like it should interfere if there's any collisions), nor how people play 3D first person games with the arrow keys. Good thing assignable keybinds exist now, otherwise you'd have to dance over the crane console to load your reactor.
9. I can check the attic among for old textbooks, are you perhaps interested in my homework assignments from 5 years ago?

**Comment by GregoriusT** [comment]
I will answer the ones which seem to need a reply. ^^

5. Lol, that "canon" composition is probably not even released yet (I was annoyingly busy for a while, and my Main Tester was busy fighting his ISP), and I can still easily change Material Compositions. So if you consider the Desh-Ready™ Blend as the Galacticraft Desh, I can fix that easily on my end, and "WorkersAlloy" is actually an unused name. ;)
Also holy crap your Desh Alloy is hell for people who try to use my Crucible to make it. Lithium and Mercury both have a very low Boiling Point, while other Stuff has a Melting Point of over 2750 Kelvin.

6. Star Wars?! All that my search originally found was that Galacticraft made it up.

7. Hehe, so I presume you dont know what SiivaGunner is, then. It is basically "take Video Game Music, take OTHER Video Game Music, take Memes and blend them together" with the result being like 20% actually good remixed Music, and the rest, well at least it has Memes! XD

8. That is because Minecraft uses an Outdated Version of LWJGL and not only that, it uses it wrongly too!

9. Nah, no need, I just find it funny that you ask people to solve Maths before they post an Issue, just to see if they are qualified enough to use the Mod.

**Comment by Troodontid** [comment]
Not related to the issue, but X=5.

**Comment by ghost** [comment]
and x=-3-sqrt(34) too 
I've checked this with wolfram alpha.😆
